# Conexion a la base de datos de IrisDual
spring.datasource.url=jdbc:mysql://localhost:3306/irisdual_db
spring.datasource.username=root
spring.datasource.password=EnderJack379

# Mostrar el SQL en la consola para hacer debugging
spring.jpa.show-sql=true

# Estrategia de generacion de tablas
spring.jpa.hibernate.ddl-auto=update

# Propiedad requerida por la catedra para mantener la sesion abierta
spring.jpa.open-in-view=true